project_id = "xjlgzxaukgshcytevdin"

 [functions.get-download-urls]
 verify_jwt = false
 
[functions.generate-license-pdf]
verify_jwt = false

[functions.send-offer-notification]
verify_jwt = false

[functions.send-offer-response]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-stripe-session]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false
